### ISSUE TITLE
The hue slider bar sometimes shows up as white on chrome 

### ISSUE THREAD

**Issue by arkhamRejek** [aesoper101/vue3-colorpicker#44]
I'm seeing that the hue slider is white. I fixed it by updating the css on my end 

<img width="346" alt="image" src="https://user-images.githubusercontent.com/7788295/229304335-81b2760a-1f56-404f-998c-367367679eda.png">

I'm not sure if it's just the framework combinations i'm using 
* Vue
* Nuxt
* Tailwind

Some css is definitely overriding it but i couldn't find it off the quick glance 

the odd thing is the **-ms-linear-gradient** is being applied although i'm using a chrome browser

<img width="497" alt="image" src="https://user-images.githubusercontent.com/7788295/229304949-22d35b6d-05d4-4115-af25-406ac06c30cf.png">

I fixed it by adding this to my css :
```css

.vc-hue-slider__bar {
  background: linear-gradient(
    to left,
    red 0%,
    yellow 16.66%,
    lime 33.33%,
    aqua 50%,
    blue 66.66%,
    fuchsia 83.33%,
    red 100%
  );
}
```

It looks like it's being dynamically set on this line of code:
https://github.com/aesoper101/vue3-colorpicker/blob/6ba66e81fe8b408f9d34ce83a9b91aa5c1d9405f/packages/common/Lightness.vue#LL87C9-L87C9

so we could add: 

```css
`linear-gradient(to left, rgb(255, 255, 255), ${color1}, ${color2}, ${color3}, ${color4}, rgb(0, 0, 0))`,
```

but I'm not sure if that's the actual issue since I didn't have time to dig too deep
